### PR TITLE
Spec with no spec title

### PR DESCRIPTION
**Pull request by babalubas090**
Added the possibility to have specs without the specTitle use in the definition of the spec

### CODE REVIEW

**Comment by babalubas090** [comment]
@BBE78 could you run the workflow again?

**Comment by babalubas090** [comment]
@BBE78 could you run the workflow again?

**Comment by BBE78** [comment]
Hi @babalubas090 , it seems that your trick is only compatible with Cypress >= v6.x...

**Comment by babalubas090** [comment]
Hi @BBE78! 
Unfortunately yes, but I didn't have the time to check it again.
Can you suggest something? Perhaps making the use of the `specTitle ` optional when dealing with Cypress >= v6.x...

**Comment by BBE78** [comment]
This PR is deprecated since PR#32

**Pull request closed without merging**
